# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# set these to deactivate `github-metadata` lookup
github:      []
title:       "jeberle.github.io"
description: ""
url:         "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl:     "" # the subpath of your site, e.g. /blog

#email: your-email@example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
#theme: minima

# this _is_ the default theme used by GitHub pages, locally at:
#   /usr/local/lib/ruby/gems/3.2.0/gems/jekyll-theme-primer-0.6.0/
remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
