= Excel Keys
:experimental:

== Selection

kbd:[Sh+<Space>]:  Select Row / Table Row

kbd:[Ctrl+<Space>]: Select Column / Table Column

kbd:[Ctrl+<Star>]: Select contiguous cells

== Worksheet Edits

kbd:[Cmd+<Plus>]: Insert Cells, Rows, Cols (quantity of whatever is selected)

kbd:[Cmd+<Minus>]: Delete Cells, Rows, Cols (whatever is selected)

== Navigation / UI

kbd:[Ctrl+<Up, Down, Left, Right>]: Go to next boundary of continguous cells

kbd:[Ctrl+<Home>]: Go to top-left corner

kbd:[Ctrl+<End>]: Go to bottom-right corner (outermost modified cell)

kbd:[Opt+Cmd+R]: Toggle Ribbon

kbd:[Opt+Left / Right]: Switch to Prev / Next Worksheet Tab

kbd:[Ctrl+F]: Find

== Values / Formulas

kbd:[F2]:  Edit cell contents

kbd:[Cmd+D]: Fill (or copy) down

kbd:[Cmd+R]: Copy Right

kbd:[Sh+F3]: Formula Builder 

kbd:[Opt+Cmd+<Equals>]: Autosum

kbd:[Ctrl+<Semi>]: Insert current date

== Edit Mode

kbd:[F2]: Toggle between Point and Edit mode

kbd:[F4 / Cmd+T]: Cycle through Absolute, AbsRow, AbsCol, Relative addressing

kbd:[Cmd+R]: Align Right

kbd:[Tab]: Tab-complete selection drop-down

== Tables

kbd:[Cmd+T]: Create Table

kbd:[Sh+Ctrl+L]: Toggle Table Filter buttons

== Names

Name columns, ranges, as well as cells. They work like worksheet-level Table refs

kbd:[Ctrl+G / F5]: Goto Name

kbd:[F3]: Paste Name 

kbd:[Cmd+F3]: Name Manager

menu:Insert[Name > Define Name...]

== Various

- Right drag corner for options on fill
- Paste Special: Add -> adds value from clipboard to paste range
- Select cell w/ desired format. "Paint Format" other cells to copy formatting
- Select range, enter 1st value, Shift-enter to fill all cells w/ value
- Use `INDEX` & `MATCH` instead of `VLOOKUP`, `HLOOKUP`

https://support.microsoft.com/en-us/office/keyboard-shortcuts-in-excel-1798d9d5-842a-42b8-9c99-9b7213f0040f[Keyboard shortcuts in Excel]
